using System;
using System.Windows.Threading;
using CommunityToolkit.Mvvm.ComponentModel;

namespace VRCDroneOSC.ViewModels;

public partial class RatesViewModel : ObservableObject
{
    private readonly MainViewModel _main;
    private readonly DispatcherTimer _uiTimer;

    // Throttle
    [ObservableProperty] private double _throttleMid;
    [ObservableProperty] private double _throttleExpo;

    // Pitch
    [ObservableProperty] private double _pitchCenter;
    [ObservableProperty] private double _pitchMaxRate;
    [ObservableProperty] private double _pitchExpo;
    [ObservableProperty] private double _pitchCurrentInput;

    // Roll
    [ObservableProperty] private double _rollCenter;
    [ObservableProperty] private double _rollMaxRate;
    [ObservableProperty] private double _rollExpo;
    [ObservableProperty] private double _rollCurrentInput;

    // Yaw
    [ObservableProperty] private double _yawCenter;
    [ObservableProperty] private double _yawMaxRate;
    [ObservableProperty] private double _yawExpo;
    [ObservableProperty] private double _yawCurrentInput;

    public RatesViewModel(MainViewModel main)
    {
        _main = main;
        LoadFromProfile();

        _uiTimer = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(33) };
        _uiTimer.Tick += (_, _) => UpdateLiveInputs();
        _uiTimer.Start();
    }

    private void LoadFromProfile()
    {
        var profile = _main.ActiveProfile;

        ThrottleMid  = profile.ThrottleRate.Mid;
        ThrottleExpo = profile.ThrottleRate.Expo;

        PitchCenter  = profile.PitchRate.Center;
        PitchMaxRate = profile.PitchRate.MaxRate;
        PitchExpo    = profile.PitchRate.Expo;

        RollCenter  = profile.RollRate.Center;
        RollMaxRate = profile.RollRate.MaxRate;
        RollExpo    = profile.RollRate.Expo;

        YawCenter  = profile.YawRate.Center;
        YawMaxRate = profile.YawRate.MaxRate;
        YawExpo    = profile.YawRate.Expo;
    }

    private void UpdateLiveInputs()
    {
        var loop = _main.FlightLoop;
        if (loop == null) return;

        // Convert signed stick values to absolute magnitude for the curve graph (0..1)
        PitchCurrentInput = Math.Abs(loop.StickPitch);
        RollCurrentInput  = Math.Abs(loop.StickRoll);
        YawCurrentInput   = Math.Abs(loop.StickYaw);
    }

    private void SaveToProfile()
    {
        var profile = _main.ActiveProfile;

        profile.ThrottleRate.Mid  = ThrottleMid;
        profile.ThrottleRate.Expo = ThrottleExpo;

        profile.PitchRate.Center  = PitchCenter;
        profile.PitchRate.MaxRate = PitchMaxRate;
        profile.PitchRate.Expo    = PitchExpo;

        profile.RollRate.Center  = RollCenter;
        profile.RollRate.MaxRate = RollMaxRate;
        profile.RollRate.Expo    = RollExpo;

        profile.YawRate.Center  = YawCenter;
        profile.YawRate.MaxRate = YawMaxRate;
        profile.YawRate.Expo    = YawExpo;

        _main.SaveConfig();
    }

    // Called by partial property-changed hooks generated by MVVMTK
    partial void OnThrottleMidChanged(double value)  => SaveToProfile();
    partial void OnThrottleExpoChanged(double value) => SaveToProfile();

    partial void OnPitchCenterChanged(double value)  => SaveToProfile();
    partial void OnPitchMaxRateChanged(double value) => SaveToProfile();
    partial void OnPitchExpoChanged(double value)    => SaveToProfile();

    partial void OnRollCenterChanged(double value)   => SaveToProfile();
    partial void OnRollMaxRateChanged(double value)  => SaveToProfile();
    partial void OnRollExpoChanged(double value)     => SaveToProfile();

    partial void OnYawCenterChanged(double value)    => SaveToProfile();
    partial void OnYawMaxRateChanged(double value)   => SaveToProfile();
    partial void OnYawExpoChanged(double value)      => SaveToProfile();
}
